# Generated by Django 4.0.1 on 2022-10-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodsales',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Region', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('UnitPrice', models.FloatField()),
                ('OrderDate', models.DateTimeField(default=0)),
            ],
        ),
    ]
